"""transactions update

Revision ID: 48add7eac978
Revises: d15e33ed74b2
Create Date: 2025-04-01 14:16:57.346545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48add7eac978'
down_revision: Union[str, None] = 'd15e33ed74b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('PAID', 'CANCELED', name='transactionstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PAID', 'CANCELED', name='transactionstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
