"""update user role

Revision ID: d15e33ed74b2
Revises: e661662c8c47
Create Date: 2025-03-31 16:13:47.546788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd15e33ed74b2'
down_revision: Union[str, None] = 'e661662c8c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CASHIER', 'ACCOUNTANT', 'ADMIN', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CASHIER', 'ACCOUNTANT', 'ADMIN', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
